### ISSUE TITLE
SDK issue checklist

### ISSUE THREAD

**Issue by erlend-sh** [jMonkeyEngine/sdk#7]
_From @shadowislord on September 4, 2015 18:45_

(Note: consider splitting these into separate issues)
- [x] The bundled Blender 2.75a is not supported - exported models crash the SDK. One option is to simply update to an older Blender version such as 2.74.
- [x] Projects from 3.0 SDK are not compatible with 3.1 SDK. For example, native deployment and names of the libraries have changed - hence recreating the project is required.
- [x] The built-in documentation which is generated from the wiki has broken links - the generator has not been adjusted to the new wiki structure yet. As a result, the welcome page still says "You're using the latest version of jMonkeyEngine SDK (3.0)"
- [X] The terrain editor no longer works correctly - erasing a texture does not work. Also the paint brush seems to be offset a bit from where the mouse is. Fixed in edd183a2be86af90f5bea680fc2b953d8bf0177f
- [ ] In the "Projects" tab, importing a new asset causes it to be selected under "Dependencies" instead of under "Assets".
- [x] The editor is based on NetBeans 8.0, but NetBeans 8.1 has already been released. (Fixed in ﻿[03998b0](https://github.com/jMonkeyEngine/sdk/commit/03998b0b34b86f6aca0488e4c7bc9c68736fd010) )

_Copied from original issue: jMonkeyEngine/jmonkeyengine#329_

**Comment by erlend-sh** [comment]
_From @grizeldi on February 23, 2016 7:0_

Which of those have been fixed so far? I might see if I can help later this week.

**Comment by erlend-sh** [comment]
_From @MeFisto94 on February 23, 2016 15:8_

Well, I am currently working on porting to 8.1 (it compiles, I only have to fix some warnings).
The Blender Issue has been solved (afaik, atleast it doesn't crash anymore)

So it would be nice if you could look into that projects thing or the imported projects (though I am uncertain with that: Should we simply overwrite the old lib names with the new ones, or maybe have consistent lib names (If possible))

**Comment by erlend-sh** [comment]
_From @grizeldi on February 24, 2016 20:47_

So today I managed to fix the most trivial (welcome to jme3.0) one. PR follows as soon as I figure out how to make a build of SDK and test it out.
For really complex stuff you can't really count on me because I lack of programming experience and more important: time.

**Comment by erlend-sh** [comment]
_From @grizeldi on February 27, 2016 20:18_

Just checked the documentation generator and it also seems to be updated to the "now not so new anymore" wiki structure.
With that I think #3 is done when/if my PR is accepted.

**Comment by erlend-sh** [comment]
_From @grizeldi on February 27, 2016 20:19_

I mean number 3 on the list not issue #3... Darn github do you have to auto detect issues -.-

**Comment by grizeldi** [comment]
Hey @MeFisto94 are we done with all of this?

**Comment by MeFisto94** [comment]
Number 5 isn't even listed as an issue yet I guess.
Number 2 is in my repo but before breaking users' projects we should maybe do some more testing and especially: Reformulate the text

Regarding Number 3: Are you sure about the structure? As in: Full documentation available, links between working?

**Comment by MeFisto94** [comment]
So Number 5 is actually only a "display bug".
It gets added under Assets but it'll be selected under Dependencies aswell (Assets actually are a runtime dependency and needed for Tab Completion).

**Comment by grizeldi** [comment]
Regarding num 3: Just tested it and it seems to work. Both locally and online.

**Comment by grizeldi** [comment]
Any progress on number 5? It's driving me nuts. So annoying!
Where is that implemented? I might take a look at it.

**Comment by normen** [comment]
There is nothing "implemented" for this, its built into NetBeans, I already asked about this on their forum but got no answer.

**Comment by MeFisto94** [comment]
Actually it's also wrongly formulated:
It is under Assets and under Dependencies (since each Asset is actually a Runtime Dependency).

The only thing is that it seems to open the dependencies before Assets now so maybe it's enough to just close the Dependency Windows, don't know.
And the Assets are actually a custom node just like the important files tutorials for netbeans

**Comment by MeFisto94** [comment]
Closing this issue as the only remaining issue exists for more than 4 years and all the others have been closed.
See #62 and #98 for details
